### ISSUE TITLE
installing model : llama3.1 error verifying model:  downloaded model directory does not contain the manifest file

### ISSUE THREAD

**Issue by ALAWIII** [amirrezaDev1378/ollama-model-direct-download#4] opened 2024-10-07 10:39 UTC
/home/allawiii/Downloads/omdd-linux-amd64  get llama3.1:latest
get direct download link for model : llama3.1:latest
Manifest download link: https://registry.ollama.ai/v2/library/llama3.1/manifests/latest
Download links for layers:
1- https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
2- https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:948af2743fc78a328dcb3b0f5a31b3d75f415840fdb699e8b1235978392ecf85
3- https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:0ba8f0e314b4264dfd19df045cde9d4c394a52474bf92ed6a3de22a4ca31a177
4- https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:56bb8bd477a519ffa694fc449c2413c6f0e1d3b1c88fa7e3c9d88d3ae49d4dcb
5- https://registry.ollama.ai/v2/library/llama3.1/blobs/sha256:1a4c3c319823fdabddb22479d0b10820a7a39fe49e45c40bae28fbe83926dc14
Generated download links for model :  llama3.1:latest finished successfully.

╰─λ ls
.rw-r--r--  859 allawiii  7 Oct 13:28  latest
.rw-r--r--  12k allawiii  7 Oct 13:29  sha256:0ba8f0e314b4264dfd19df045cde9d4c394a52474bf92ed6a3de22a4ca31a177
.rw-r--r--  485 allawiii  7 Oct 13:30  sha256:1a4c3c319823fdabddb22479d0b10820a7a39fe49e45c40bae28fbe83926dc14
.rw-r--r-- 4.7G allawiii  6 Oct 20:47  sha256:8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
.rw-r--r--   96 allawiii  7 Oct 13:29  sha256:56bb8bd477a519ffa694fc449c2413c6f0e1d3b1c88fa7e3c9d88d3ae49d4dcb
.rw-r--r-- 1.5k allawiii  7 Oct 13:29  sha256:948af2743fc78a328dcb3b0f5a31b3d75f415840fdb699e8b1235978392ecf85

here is the command and the output:

sudo /home/allawiii/Downloads/omdd-linux-amd64  install --model=llama3.1 --blobsPath=/home/allawiii/Desktop/modela/
installing model : llama3.1
error verifying model:  downloaded model directory does not contain the manifest file

**Comment by amirrezaDev1378** [comment] 2024-10-07 11:50
Hello,

The issue you're encountering is caused by the name of the manifest file. Please rename the file from "latest" to "manifest" and try again.

I’ve noticed that the relevant section of the documentation isn’t as clear as it should be. I’ll be updating it with additional information.

@ALAWIII

**Comment by ALAWIII** [comment] 2024-10-07 12:33
I successfully installed the model , but there is a problem :

`sudo /home/allawiii/Downloads/omdd-linux-amd64 install --model=llama3.1 --blobsPath=/home/allawiii/Desktop/modela/`

output:

> installing model : llama3.1
> 2024/10/07 15:25:11 Using default model tag if you encountered any error while using ollama try to install it with the acutal tag e.g. llama:16b
> 2024/10/07 15:25:11 /usr/share/ollama/.ollama/models
> 2024/10/07 15:25:11 Copying blobs to /usr/share/ollama/.ollama/models/blobs
> 2024/10/07 15:25:11 This may take a while so dont worry the program is not stuck
> Model installed successfully

but when checking whether its detected by the Ollama ,I get nothing:

`╰─λ ollama list`

> NAME    ID    SIZE    MODIFIED

I installed ollama tool and `enabled/started the services` from arch official repo :
https://archlinux.org/packages/extra/x86_64/ollama/

also when using the command :

> `ollama run llama3.1`

  
it go and redownload the whole model from scratch which its size 4.7gb

**Comment by amirrezaDev1378** [comment] 2024-10-07 12:47
Do you see any blobs copied into usr/share/ollama/.ollama/models/blobs ?

**Comment by ALAWIII** [comment] 2024-10-07 12:58
> ` ls /usr/share/ollama/.ollama/models/blobs`


`.rw-r--r--  12k root  7 Oct 15:25`  sha256::0ba8f0e314b4264dfd19df045cde9d4c394a52474bf92ed6a3de22a4ca31a177
`.rw-r--r--  485 root  7 Oct 15:25 ` sha256::1a4c3c319823fdabddb22479d0b10820a7a39fe49e45c40bae28fbe83926dc14
`.rw-r--r-- 4.7G root  7 Oct 15:25`  sha256::8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe
`.rw-r--r--   96 root  7 Oct 15:25`  sha256::56bb8bd477a519ffa694fc449c2413c6f0e1d3b1c88fa7e3c9d88d3ae49d4dcb
`.rw-r--r-- 1.5k root  7 Oct 15:25 ` sha256::948af2743fc78a328dcb3b0f5a31b3d75f415840fdb699e8b1235978392ecf85



> `ls /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/llama3.1/`
> 
> `.rw-r--r-- 859 root  7 Oct 15:25 ` latest

**Comment by amirrezaDev1378** [comment] 2024-10-07 13:06
Models are where they should be. did you set a custom path for ollama models?

https://github.com/ollama/ollama/blob/main/docs/faq.md#where-are-models-stored

**Comment by ALAWIII** [comment] 2024-10-07 13:07
no I didnt play with the settings , should I set a custom path ?

**Comment by ALAWIII** [comment] 2024-10-07 13:09
I found a .ollama directory hidden in my home directory :


> `ls /home/allawiii/.ollama/models/blobs/`

.rw-r--r-- 4.7G allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial
.rw-r--r--   55 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-0
.rw-r--r--   63 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-1
.rw-r--r--   63 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-2
.rw-r--r--   63 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-3
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-4
.rw-r--r--   64 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-5
.rw-r--r--   64 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-6
.rw-r--r--   64 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-7
.rw-r--r--   64 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-8
.rw-r--r--   64 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-9
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-10
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-11
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-12
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-13
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-14
.rw-r--r--   65 allawiii  7 Oct 15:16  sha256-8eeb52dfb3bb9aefdf9d1ef24b3bdbcfbe82238798c4b918278320b6fcef18fe-partial-15

**Comment by amirrezaDev1378** [comment] 2024-10-07 13:10
As mentioned here https://github.com/ollama/ollama/issues/733 apparently ollama stores model  in a different directory for some linux distros.

The best solution that I can think of is setting an environment variable to where ollama stores its models.

You can set `OLLAMA_MODELS ` environment variable **globally** to set where you want to store your models.

**Comment by ALAWIII** [comment] 2024-10-07 13:52
I am using systemd:
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server

the contents of the given path is :
`/etc/systemd/system/multi-user.target.wants/ollama.service`

> [Unit]
> Description=Ollama Service
> Wants=network-online.target
> After=network.target network-online.target
> 
> [Service]
> ExecStart=/usr/bin/ollama serve
> WorkingDirectory=/var/lib/ollama
> Environment="HOME=/var/lib/ollama"
> `Environment="OLLAMA_MODELS=/var/lib/ollama"`
> User=ollama
> Group=ollama
> Restart=on-failure
> RestartSec=3
> RestartPreventExitStatus=1
> Type=simple
> PrivateTmp=yes
> ProtectSystem=full
> ProtectHome=yes
> 
> [Install]
> WantedBy=multi-user.target
>

**Comment by ALAWIII** [comment] 2024-10-07 14:21
sadly there is nothing I have in my head to do ! 
thanks anyway brother, you helped me a lot to pass 90% of the problem ❣️

**Comment by amirrezaDev1378** [comment] 2024-10-07 15:35
No, as I said earlier you should set `OLLAMA_MODELS` globally,
You have only set it for the ollama language server.
Since you already set it for the ollama language server you can export it in your terminal before running the command again.

This is an Ollama issue but let me know if I can help with anything related.

**Comment by ALAWIII** [comment] 2024-10-07 15:39
I am on garuda which is arch-based distro !
I am using fish shell , adding a environment variable globally :
`set -U OLLAMA_MODELS "/var/lib/ollama"`

╰─λ echo $OLLAMA_MODELS
/var/lib/ollama

-----
nothing changed and I still facing the same problem , by the way I found a repo that has uploaded multiple zipped ollama models ,I am downloading one of the models to experiment !

**Comment by amirrezaDev1378** [comment] 2024-10-07 17:16
Good lock with that @ALAWIII .
I believe this is an issue with ollama and your distro.
Install command will only do two things:

- Do a basic verification of files you have downloaded 
- Copy the manifest and other model files

**Comment by amirrezaDev1378** [comment] 2024-10-07 17:17
Closing this issue becuase I believe this is an issue with the ollama itself.

Feel free to open another issue if you have another problem.

**Closed as completed by amirrezaDev1378** 2024-10-07 17:17 UTC
Labels: documentation

**Comment by ALAWIII** [comment] 2024-10-07 17:35
yes you are right  its an ollama issue , I did a lot of experiments which proves this  and its hard to 
summarize this ,
thank you anyway bro ❣️
